config/routes.rb
Rails.application.routes.draw do

  root 'static#index'

  # get 'static/about'
  # get 'static/contacts'

  resources :clients

  resources :categories
  resources :tags

 #resources :bannerz, only: [:index]
  match 'bannerz', to: 'banners#index', via: :get, as: 'banners_index'


  resources :platforms
  match 'platforms/:id/start/', to: 'platforms#start', via: :get, as: 'platform_start'

  resources :places


  #resources :shows

  resources :statuses, only: [:index, :show]

end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController
  def index
    @platforms = Platform.all
  end

  def show
    @platform = Platform.find params[:id]
  end

  def new
    @platform = Platform.new
  end

  def create
    @platform = Platform.new platform_params

    if @platform.save
      flash[:notice] = 'Platform created'
      redirect_to platforms_path
    else
      flash.now[:warning] = 'There were problems when trying to create a new platform'
      render action: :new
    end
  end

  def edit
    @platform = Platform.find params[:id]
  end

  def update
    @platform = Platform.find params[:id]

    if @platform.update_attributes platform_params
      flash[:notice] = 'Platform has been updated'
      redirect_to platforms_path
    else
      flash.now[:warning] = 'There were problems when trying to update this platform'
      render action: :edit
    end
  end

  def destroy
    @platform = Platform.find params[:id]

    @platform.destroy
    flash[:notice] = 'Platform has been deleted'
    redirect_to platforms_path
  end

  def start

    @platform = Platform.find params[:id]
    interval = "#{@platform.interval}s"

    ENV['TZ'] = 'Asia/Astana'
    job_id =
        Rufus::Scheduler.singleton.every interval do

          Show.visit(@platform)

        end

    puts "scheduled job #{job_id}"
    redirect_to platforms_path

  end

  private

  def platform_params
    params.require(:platform).permit(:title, :link, :description, :timeout, :interval)
  end
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/views/platforms/_form.html.slim
== simple_form_for @platform do |f|

  div.input-field
    == f.input :title, label: 'Title'

  div.input-field
    == f.input :link, label: 'Link'

  div.input-field
    == f.input :interval, label: 'Interval'

  div.input-field
    == f.input :timeout, label: 'Timeout'

  div.input-field
    == f.input :description, label: 'Description', as: :text, required: false, input_html: { class: 'materialize-textarea' }

  == f.button :submit, input_html: {class: 'btn waves-effect waves-light'}
  | &nbsp;
  == link_to 'Cancel', platforms_path, class: 'btn waves-effect waves-light'

app/views/platforms/_list.html.slim
table.striped
  thead
    tr
      th Title
      th Description
      th
      th

  tbody
    - @platforms.each do |platform|
      tr
        td
          == platform.title
          br
          == link_to platform.link, platform.link, target: '_blank'
        td = platform.description
        td
          / link_to ('<i class="material-icons view">info_outline</i> ').html_safe, new_category_path(category.id), target: '_blank'
          == link_to ('<i class="material-icons edit">mode_edit</i> ').html_safe, edit_platform_path(platform.id)
          == link_to ('<i class="material-icons delete">delete</i> ').html_safe, platform_path(platform.id), method: 'delete', data: {confirm: 'Are you sure?'}, class: 'delete'
        td
          == link_to ('Start ').html_safe, platform_start_path(platform.id), class: 'waves-effect waves-light btn'

app/views/platforms/edit.html.slim
h3 Edit Platform
== render partial: 'form'

app/views/platforms/index.html.slim
h3 Platforms
==link_to 'Create new Platform', new_platform_path, class: 'waves-effect waves-light btn'
== render partial: 'list'

app/views/platforms/new.html.slim
h1 Create new Platform
== render partial: 'form'

app/views/platforms/show.html.slim
h1 Platforms#show
p Find me in app/views/platforms/show.html.slim