config/routes.rb
Rails.application.routes.draw do

  root 'static#index'

  # get 'static/about'
  # get 'static/contacts'

  resources :clients

  resources :categories
  resources :tags

 #resources :bannerz, only: [:index]
  match 'bannerz', to: 'banners#index', via: :get, as: 'banners_index'


  resources :platforms
  match 'platforms/:id/start/', to: 'platforms#start', via: :get, as: 'platform_start'

  resources :places


  #resources :shows

  resources :statuses, only: [:index, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/banner.rb
class Banner < ApplicationRecord

  # relations
  belongs_to :platform
  belongs_to :place
  belongs_to :client

  has_many :shows

  # validations

end

app/models/category.rb
class Category < ApplicationRecord
  # relations
  #belongs_to :category, optional: true

  # validations

end

app/models/client.rb
class Client < ApplicationRecord

  # relations
  has_many :banners
  has_many :shows

  # validations

end

app/models/crono_job.rb
class CronoJob < ApplicationRecord
end

app/models/place.rb
class Place < ApplicationRecord

  # relations
  has_many :banners
  has_many :shows

  belongs_to :platform

  # validations

end

app/models/platform.rb
class Platform < ApplicationRecord

  # relations
  has_many :places
  has_many :banners

  has_many :shows

  # validations

end

app/models/show.rb
class Show < ApplicationRecord

  # relations
  belongs_to :platform
  belongs_to :place
  belongs_to :banner
  belongs_to :client

  # validations


  # methods
  def self.visit(platform)

    @current_platform = platform
    @timeout = 3000

    # platform

    # one visit
    @visit = `phantomjs ./vendor/collector.js #{@current_platform.link} #{@current_platform.timeout}`
    visit = @visit.split('=======')
    visit_result = JSON.parse visit[1]


    # Each visit results
    visit_result.each do |show|

      #puts '====='
      #puts banner_hash
      #puts show[0]    # ID
      #puts show[1]    # Name
      #puts show[2]    # Width
      #puts show[3]    # Height
      #puts show[4]
      #puts show[5]
      #puts show[6][0] # google_ads_iframe_
      #puts show[6][1] # google_id
      #puts show[6][2] # place_name
      #puts show[7]    # html
      #puts show[8]    # base64 screenshot
      #puts '====='

      # Place
      @current_place = Place.find_or_create_by(html_id: show[0]) do |place|
        place.title         = show[0]
        place.html_id       = show[0]
        place.html_name     = show[1]
        place.html_title    = show[6][2]
        place.width         = show[2]
        place.height        = show[3]
        place.google_id     = show[6][1]
        place.google_title  = show[6][2]
        place.platform_id   = @current_platform.id
      end

      #client
      # TODO: extract client link
      @current_client = Client.first

      # Banner
      #links = show[7].match(/(http|https):\/\/([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:\/~+#-]*[\w@?^=%&\/~+#-])/)
      #html = Nokogiri::HTML(show[7])
      #links = html.css('a')

      #find or create banner

      banner_hash = Digest::SHA256.hexdigest show[8]
      @current_banner = Banner.find_or_create_by(html: show[7])
      if @current_banner.new_record?
        @current_banner.width   = show[2]
        @current_banner.height  = show[3]
        @current_banner.title   = "#{@current_platform.title} - #{@current_place.google_title} (#{@current_banner.width}x#{@current_banner.height})"
        @current_banner.html    = show[7]
        @current_banner.screenshot = show[8]

        @current_banner.platform_id  = @current_platform.id
        @current_banner.place_id     = @current_place.id
        @current_banner.client_id    = @current_client.id

        @current_banner.hash_line = banner_hash
        @current_banner.save
      end

      # create one show

      @current_show = Show.new(
          platform_id:  @current_platform.id,
          place_id:     @current_place.id,
          client_id:    @current_client.id,
          banner_id:    @current_banner.id
      )
      @current_show.save

      puts '+++++++++'
      puts "Platform: #{@current_platform.errors.full_messages}"
      puts "Place: #{@current_place.errors.full_messages}"
      puts "Banner: #{@current_banner.errors.full_messages}"
      puts "Show: #{@current_show.errors.full_messages}"
      puts '+++++++++'

    end

    puts '=== One show ==='

  end

  def self.find_uniqueness(html_string)

    uniqueness = ''

    html = Nokogiri::HTML(html_string)

    images  = html.css('img')
    links   = html.css('a')
    frames  = html.css('iframe')
    scripts = html.css('script')

    images.each do |i|

      uniqueness << i.attr(src)

    end



=begin
    useful_frames = 0

    frames.each do |f|

      unless f.attr('src') == '' || f.attr('src').include?('/safeframe/')

        useful_frames = 1

      end

    end
=end


    if images.length == 0

      if frames == 0

        if links.length == 0

          if scripts.length == 0

            # no uniqueness...

          else
            # uniq is script
            uniqueness = 'uniqueness is Script'
          end

        else
          # uniq is frame
          uniqueness = 'uniqueness is Link'
        end

      else
        # uniq is link
        uniqueness = 'uniqueness is Frame'
      end

    else
      # uniq is image
      uniqueness = 'uniqueness is Image'
    end

    # return uniqueness

  end

end

app/models/tag.rb
class Tag < ApplicationRecord

  # relations

  # validations

end

app/controllers/banners_controller.rb
class BannersController < ApplicationController
  def index

    @banners = Banner.all

  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end

  def about
  end

  def contacts
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find params[:id]
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new tag_params

    if @tag.save
      flash[:notice] = 'Tag created'
      redirect_to tags_path
    else
      flash.now[:warning] = 'There were problems when trying to create a new tag'
      render action: :new
    end
  end

  def edit
    @tag = Tag.find params[:id]
  end

  def update
    @tag = Tag.find params[:id]

    if @tag.update_attributes tag_params
      flash[:notice] = 'Tag has been updated'
      redirect_to tags_path
    else
      flash.now[:warning] = 'There were problems when trying to update this tag'
      render action: :edit
    end
  end

  def destroy
    @tag = Tag.find params[:id]

    @tag.destroy
    flash[:notice] = 'Tag has been deleted'
    redirect_to tags_path
  end

  private

  def tag_params
    params.require(:tag).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/banners/_list.html.slim
- @banners.each do |banner|
  //- uniqueness = Nokogiri::HTML(banner.html)
  .one-banner
    b == "#{banner.id}. #{banner.title} (#{banner.width}x#{banner.height})"
    /br
    /b == banner.hash_line
    /=h banner.html
    br
    == image_tag(banner.screenshot, alt: banner.title)
    br
    //b == Show.find_uniqueness banner.html
    br
    //== ap uniqueness.css('img').to_a
    //== ap uniqueness.css('iframe').to_a
    //== ap uniqueness.css('a').to_a
    //== ap uniqueness.css('script').to_a
    hr

app/views/banners/index.html.slim
h3 Banners
== render partial: 'list'

app/views/clients/_form.html.slim
== simple_form_for @category do |f|

  div.input-field
    == f.input :title, label: 'Title'

  div.input-field
    == f.input :description, label: 'Description', as: :text, required: false, input_html: { class: 'materialize-textarea' }

  == f.button :submit, input_html: {class: 'btn waves-effect waves-light'}
  == link_to 'Cancel', categories_path, class: 'btn waves-effect waves-light'

app/views/clients/_list.html.slim
ul.collection
  - @categories.each do |category|

    li.collection-item.avatar
      span.title = category.title
      p = category.description.html_safe
      div.secondary-content
        / link_to ('<i class="material-icons view">info_outline</i> ').html_safe, new_category_path(category.id), target: '_blank'
        == link_to ('<i class="material-icons edit">mode_edit</i> ').html_safe, edit_category_path(category.id)
        == link_to ('<i class="material-icons delete">delete</i> ').html_safe, category_path(category.id), method: 'delete', data: { confirm: 'Are you sure?' }, class: 'delete'

app/views/clients/edit.html.slim
h1 Clients#edit
p Find me in app/views/clients/edit.html.slim

app/views/clients/index.html.slim
h3 Clients

app/views/clients/new.html.slim
h1 Clients#new
p Find me in app/views/clients/new.html.slim

app/views/clients/show.html.slim
h1 Clients#show
p Find me in app/views/clients/show.html.slim

app/views/places/edit.html.slim
h1 Places#edit
p Find me in app/views/places/edit.html.slim

app/views/places/index.html.slim
h3 Places

app/views/places/new.html.slim
h1 Places#new
p Find me in app/views/places/new.html.slim

app/views/places/show.html.slim
h1 Places#show
p Find me in app/views/places/show.html.slim

app/views/tags/_form.html.slim
== simple_form_for @tag do |f|

  div.input-field
    == f.input :title, label: 'Title'

  div.input-field
    == f.input :description, label: 'Description', as: :text, required: false, input_html: { class: 'materialize-textarea' }

  == f.button :submit, input_html: {class: 'btn waves-effect waves-light'}
  | &nbsp;
  == link_to 'Cancel', tags_path, class: 'btn waves-effect waves-light'

app/views/tags/_list.html.slim
- @tags.each do |tag|
  == link_to tag.title, tag_path(tag.id), class: 'waves-effect waves-light btn single-tag light-blue darken-3'

app/views/tags/edit.html.slim
h3 Edit Tag
== render partial: 'tags/form'

app/views/tags/index.html.slim
h3 Tags
== link_to 'Create new Tag', new_tag_path, class: 'btn waves-effect waves-light'
.content.all-tags
  == render partial: 'tags/list'

app/views/tags/new.html.slim
h1 Create new Tag
== render partial: 'tags/form'

app/views/tags/show.html.slim
h3 == @tag.title
p == @tag.description
p
  == link_to 'edit', edit_tag_path(@tag.id), class: 'btn waves-effect waves-light'
  | &nbsp;
  == link_to 'delete', tag_path(@tag.id), method: 'delete', data: { confirm: 'Are you sure?' }, class: 'btn waves-effect waves-light'
  | &nbsp;
  == link_to 'back', tags_path, class: 'btn waves-effect waves-light'